version: "3.7"

services:
  listing:
    build: .
    image: node:12-alpine
    working_dir: /reburke-proxy-one
    command: sh -c "npm install --production"
    ports:
      - "80:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/reburke-proxy-one
    command: sh -c "npm start"
